export const QUERY_METHODS = [
  "countDocuments",
  "deleteMany",
  "deleteOne",
  "find",
  "findOne",
  "findOneAndDelete",
  "findOneAndRemove",
  "findOneAndUpdate",
  "remove",
  "update",
  "updateOne",
  "updateMany",
  "save",
];
